Re-branding kcm

diff --git a/kbcm-1.0.4/progress_bar b/kbcm-1.0.4/progress_bar
--- a/kbcm-1.0.4/progress_bar
+++ b/kbcm-1.0.4/progress_bar
@@ -1,7 +1,8 @@
 #!/bin/bash
 #kiran.vkvr@gmail.com
-#https://github.com/Kiran-Bose/kcm
+#https://github.com/Kiran-Bose/kbcm
 
+kbcmversion="1.0.4"
 #------------------------------------------------------------------------------------------------
 function kbbar ()
 {
@@ -16,7 +17,10 @@ if [ "$1" == "$2" ] || [ "$tots" == 0 ]
 then
 return
 fi
+if [[ ! -d "$2" ]] || [[ ! -f "$2" ]]
+then
 sleep 1
+fi
 if [[ (-d "$2") || (-f "$2") ]] && [ $tots != 0 ]
 then
 	if [[ ("$1" == "/media/$user"*) && ("$2" == "/media/$user"*) ]]
@@ -47,26 +51,42 @@ fs2=$(df "$chk2" | awk '{print $1}' | sed 1d)
 	while echo "($ptg < 99)" | bc | grep -q 1
 	do
 	totd=0
-		if [[ "$2" == *"/1000/gvfs/mtp"* ]]
+		if [[ (-d "$2") || (-f "$2") ]]
 		then
-		IFS=$'\n' read -rd '' -a arraysz1 <<< `ls -Ral "$2" | awk '{print $5}' | sed 's/[^0-9]*//g'` 
+			if [[ "$2" == *"/1000/gvfs/mtp"* ]]
+			then
+			IFS=$'\n' read -rd '' -a arraysz1 <<< `ls -Ral "$2" | awk '{print $5}' | sed 's/[^0-9]*//g'` 
+			else
+			IFS=$'\n' read -rd '' -a arraysz1 <<< `sudo ls -Ral "$2" | awk '{print $5}' | sed 's/[^0-9]*//g'` 
+			fi
+			for ((i=0; i<${#arraysz1[@]}; i++)); do
+			totd=$(($totd + "${arraysz1[$i]}"))	
+			done
+		echo -en "\0015"
+		ds=$totd
+		ptg=$( echo "scale=6; $ds/$ss * 100" | bc )
+		sptg=${ptg%.*}
+		clb=$( echo "$ptg/2" | bc )
+			if(($sptg>100)) > /dev/null 2>&1
+			then
+			echo -en "\e[44;97;10;82m 100% \e[0m\e[89m \e[0m"
+				for i in `seq 1 50`
+				do
+				echo -en "$COMPLETED"
+				done
+				echo -e "\n"
+			return
+			fi
+		echo -en "\e[44;97;10;82m  $sptg% \e[0m\e[89m \e[0m"
+			for i in `seq 1 $clb`
+			do
+			echo -en "$COMPLETED"
+			done
 		else
-		IFS=$'\n' read -rd '' -a arraysz1 <<< `sudo ls -Ral "$2" | awk '{print $5}' | sed 's/[^0-9]*//g'` 
+		echo -e "\e[91mTransfer error/Device disconnected\e[0m"
+		return
 		fi
-		for ((i=0; i<${#arraysz1[@]}; i++)); do
-		totd=$(($totd + "${arraysz1[$i]}"))	
-		done
-	echo -en "\0015"
-	ds=$totd
-	ptg=$( echo "scale=6; $ds/$ss * 100" | bc )
-	sptg=${ptg%.*}
-	clb=$( echo "$ptg/2" | bc )
-	echo -en "\e[44;97;10;82m  $sptg% \e[0m\e[89m \e[0m"
-	for i in `seq 1 $clb`
-	do
-	echo -en "$COMPLETED"
-	done
-	sleep 0.1
+	sleep 0.18
 	done
 	echo -en "\0015"
 	echo -en "\e[44;97;10;82m 100% \e[0m\e[89m \e[0m"
