* Progress bar infinite loop bug fix * File system determination code fix * Code optimization

diff --git a/kbcm-1.0.5/kbcm b/kbcm-1.0.5/kbcm
--- a/kbcm-1.0.5/kbcm
+++ b/kbcm-1.0.5/kbcm
@@ -55,7 +55,7 @@ while getopts ":cmv" option; do
   	case "${option}" in
 	c)actn="cp -rv";;
 	m)actn="mv -v";;
-	v)echo -e "version 1.0.4" && exit 0;;
+	v)echo -e "version 1.0.5" && exit 0;;
 	\?)kbcmusage && exit 0;;
 	esac
 done
@@ -71,13 +71,21 @@ else
 feedemt=$(echo "$2" | rev | cut -d '/' -f 1 | rev)
 echo -e "________________________________________________________________________________"
 echo "$2 --> $3"
-$actn "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots"
+$actn "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots" || exit 1
 	if [[ ${PIPESTATUS[0]} == 1 ]]
 	then
-	echo -e "________________________________________________________________________________"
-	echo "$2 --> $3"
-	sudo $actn "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots"
-	fi 
+		tots=$(szcum "$2")
+		if [ "$tots" == "f" ]
+		then
+		echo -e "\e[91mSource path not found\e[0m"
+		exit 1
+		else
+		feedemt=$(echo "$2" | rev | cut -d '/' -f 1 | rev)
+		echo -e "________________________________________________________________________________"
+		echo "$2 --> $3"
+		sudo $actn "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots"
+		fi
+	fi
 fi
 
 
